# NumPy Exercises

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.

#### Import NumPy as np

In [3]:
import numpy as np

#### Create an array of 10 zeros

In [ ]:
arr = np.array([0, 0, 0, 0, 0, 0, 0, 0, 0])

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create an array of 10 ones

In [ ]:
arr=np.array([1,1,1,1,1,1,1,1,1,1])

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Create an array of 10 fives

In [ ]:
arr=np.array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### Create an array of the integers from 10 to 50

In [3]:
arr=np.array([range(10,51)])

#### Create an array of all the even integers from 10 to 50

In [10]:
list1=[]
for i in range(10,51):
  if i % 2==0:
    list1.append(i)
arr=np.array(list1)


#### Create a 3x3 matrix with values ranging from 0 to 8

In [4]:
arr=np.array([range(0,9)])
arr.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create a 3x3 identity matrix

In [15]:
arr=np.array([1,0,0,0,1,0,0,0,1])
arr.reshape(3,3)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

#### Use NumPy to generate a random number between 0 and 1

In [16]:
from numpy import random

x = random.rand()

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [17]:
arr=random.normal(size=(1,25))

#### Create the following matrix:

In [6]:
arr=np.arange(0.01,1.01,0.01)

#### Create an array of 20 linearly spaced points between 0 and 1:

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [7]:
arr=np.array([range(1,26)])
arr.reshape(5,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [10]:
arr=np.array([range(12,24)])
arr.reshape(3,4)

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [12]:
arr=np.array([20])

In [11]:
arr=np.array([2,7,12])
arr.reshape(3,1)

array([[ 2],
       [ 7],
       [12]])

In [13]:
arr=np.array([21,22,23,24,25])

In [14]:
arr=np.array([range(16,26)])
arr.reshape(2,5)

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

# Great Job!