# NumPy Exercises

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.

#### Import NumPy as np

In [45]:
import numpy as np

#### Create an array of 10 zeros

In [46]:
arr = np.array([0, 0, 0, 0, 0, 0, 0, 0, 0])

#### Create an array of 10 ones

In [47]:
arr1=np.array([1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0])
arr1

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Create an array of 10 fives

In [48]:
list_1=[]
for i  in range(10):
  list_1.append(5.0)
arr3=np.array(list_1)
arr3


array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### Create an array of the integers from 10 to 50

In [49]:
list_2=[]
for i  in range(10,51):
  list_2.append(i)
arr4=np.array(list_2)
arr4

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Create an array of all the even integers from 10 to 50

In [50]:
list_3=[]
for i  in range(10,51):
  if i%2==0:
    list_3.append(i)
arr5=np.array(list_3)
arr5

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Create a 3x3 matrix with values ranging from 0 to 8

In [51]:
array=np.array([[0,1,2],[3,4,5],[6,7,8]])
array

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create a 3x3 identity matrix

In [52]:
ide=np.identity(3)
ide

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Use NumPy to generate a random number between 0 and 1

In [53]:
t=np.random.rand()
x=np.array(t)
x

array(0.97362542)

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [54]:
y=np.random.randn(25)
y


array([-0.13645573, -0.72498964,  0.80495984, -0.80224814,  0.73406185,
        0.40642302, -0.88595709,  0.77869053,  0.28976305, -0.61953869,
       -0.80413154, -1.11798787,  0.31266107, -0.40377976,  0.61040267,
       -1.33462352, -0.86971675,  0.64887355, -0.77617121,  0.57812974,
       -0.17158554, -0.1111051 , -1.12972351,  1.95397204, -0.23927773])

#### Create the following matrix:

In [55]:
a=np.linspace(0.01,1.0,100)
b=a.reshape(10,10)
b

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

#### Create an array of 20 linearly spaced points between 0 and 1:

In [56]:
c=np.linspace(0,1,20)
c

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [57]:
l1=[]
for i in range(1,26):
  l1.append(i)
l2=np.array(l1)
l3=l2.reshape(5,5)
l3

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [58]:
l3[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [59]:
l3[3,4]

20

In [60]:
l4=l3[0:3,1].reshape(3,1)
l4

array([[ 2],
       [ 7],
       [12]])

In [61]:
l3[4]

array([21, 22, 23, 24, 25])

In [62]:
l3[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

# Great Job!